mailproject/maillapp/urls.py
from os import name
from django.urls import path
from .views import HomePageView, TaskDetail, TaskCreate, TaskUpdate ,TaskDelete
urlpatterns = [
    path('', HomePageView.as_view(), name='app_pge'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task_detail'), 
    path('create/', TaskCreate.as_view(), name='task_create') ,
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', TaskDelete.as_view(), name='task-update')
]
 

mailproject/mailproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maillapp.urls') )
]

mailproject/maillapp/models.py
from django.db import models
from django.contrib.auth.models import User

#databasez

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50) 
    desc = models.TextField(max_length=100, null=True, blank=True) 
    complete = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

mailproject/maillapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView  # basic listviews of objects
from django.views.generic.detail import DetailView #detail view used to show details for single single objetcs
#create views creates item in database and update views updates it
from django.views.generic.edit import CreateView ,UpdateView, DeleteView
from django.urls import reverse_lazy #to redirect the user over a page 
#lgin and logout
# #database
from .models import Task 
# model = task // task is a class in model.py // database so that it could acces the values

class HomePageView(ListView):
    model = Task
    context_object_name = 'task'
    template_name = 'maillapp/tasklist.html'
    def get_context_data(self, **kwargs):
        count = 0
        context = super().get_context_data(**kwargs)
        for item in Task.objects.all():
            if item.complete == False:
                count += 1  
        context['count'] = count
        return context

class TaskDetail( DetailView):
    model = Task
    template_name = 'maillapp/taskdetail.html' 
    
class TaskCreate( CreateView): #fo inserting objects in database
    model = Task
    template_name = 'maillapp/taskform.html' 
    fields = {'desc', 'title' } 
    success_url = reverse_lazy('app_pge')  #name of urls in ('')
    
class TaskUpdate(UpdateView): #to update already existed objects in TaskCreate
    model = Task
    fields = {'title', 'desc', 'complete'} 
    template_name = 'maillapp/taskform.html' #it searches for file which is seracged by TaskCreate
    success_url = reverse_lazy('app_pge')

class TaskDelete(DeleteView):
    model = Task
    context_object_name = 'task' 
    success_url = reverse_lazy('app_pge')
    template_name = 'maillapp/taskdelete.html' 

mailproject/maillapp/templates/maillapp/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do List Never Be Late </title>
    <!-- meta tags  -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- bootstrap  -->
    <!-- icons  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- fonts  -->
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Fira+Sans+Condensed&family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Lobster&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Fira+Sans+Condensed&family=Lobster&display=swap"
        rel="stylesheet">

    {% block editing %}

    {% endblock editing %}

    <style>
        body{
            background-color: aliceblue;

        }
.fullbody
        {
            overflow-x: hidden;
        }
        .slogan a{ text-decoration: none; color: black;}
        *{
           padding: 0%; margin: 0%;
        }
        .container {
            align-items: center;
            padding: 10px;
        }

        .navbar {
            font-family: 'Bebas Neue', cursive;
            letter-spacing: 1px;
            padding: 10px;
            display: flex;
            height: 40px;
            justify-content: space-between;
            align-items: center;
            background: linear-gradient(to right, #33ccff 0%, #ff99cc 100%);
        }
        .navbar a{ text-decoration: none; color: black; font-size: 18px; }
        .navbar ul 
        {
            display: flex;
        }
        .navbar ul li {  list-style-type: none; padding-left: 15px; }
        .barsmenu, .crossmenu{  display: none; font-size: 10px; } 
        
@media 
only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1024px)  {
    .navbar ul 
    {
        text-align: center;
        transition: .7s ease-out;
        display: block;
        position: relative;
        right: -100%;
        top: 0%; 
        width: 50%;
        background-color: cornflowerblue;
        height: 9999px;
        position: fixed;
        z-index: 1;

    }
    .navbar a:hover{  color: #33ccff; }
    .navbar { 
        display: block;
        align-items: center;
        display: flex;
    }
    .navbar ul li:first-child{ padding-top: 200px;  }
    .navbar ul li a{ margin: 10px; font-size: 2.5vh}
    .barsmenu{  display: block; z-index: 1;  } 

    .crossmenu { display: block;  position: absolute; right: 4%; top: 0%;  } 
    #checked:checked ~ ul {  right: 0%    }   
    .navbar ul li , .logo {
            font-size: 17px;
            padding: 10px 10px;      }  
    
}
    </style>
</head>

<body>
    <div class="fullbody">
    <div class = "navbar" >
        <p class='slogan'> <a href="{% url 'app_pge' %}"> ToDo-App </a>| {% block currentpage %}{% endblock currentpage %} </P> 
        <nav class="nav">           
            <input type="checkbox" style="display: none;" id="checked">
            <label class="barsmenu" for="checked" ><i style="font-size: 45px; " class="icon fa fa-bars"></i></label>        
            <ul>
                <li> <a href=""> Developer </a></li> 
                <li><a href="">About Project</a></li>  
                <li><a href=""> Research Paper</a></li> 
                <label class="crossmenu" for="checked" ><i style="font-size: 4em; " class="icon fa fa-close"></i></label>   <br>
            </ul>
        </nav>
    </div>

    {% block navbar %}

    {% endblock navbar %}
    <div class="container">

        {% block body %}

        {%endblock body%}

    </div>
</div>
</body>

</html>

mailproject/maillapp/templates/maillapp/task_list.html
{% extends 'maillapp/main.html' %}
{% block editing %}
<style>
    ::-webkit-scrollbar{ display: none;  }    
    .counts
    {
        text-align: center;
        margin-bottom: 10px;
        font-size: 20px;
        color: black;
        font-family: 'Lobster', cursive;
        margin-bottom: 30px;
    }
    .add-schedule
    {
        font-weight: 300;
        padding: 10px;
        font-size: 20px;
        padding: 10px;
        
        width: fit-content;
        display: flex;
        margin-left: auto;
        margin-right: auto;
        border: 1px solid transparent;
        background: #33ccff;
        box-shadow: 1px 3px 5px #555;
        border-radius: 4px;   margin-top:20px;  margin-bottom: 20px;
    }
    .add-schedule a {  
        color:  white;
        text-shadow: 1px 2px 4px black;
        text-decoration: none;
        padding: 10px;
    }
    .description{ display: flex;   overflow: scroll;
 box-sizing: content-box;   } 
    table { 
  width: 100%; 
  border-collapse: collapse; 
    }
 /* Zebra striping */
tr:nth-of-type(even) { 
    /* background: linear-gradient(to right, #ff99cc  0%, #33ccff 100%); */
    background: transparent;
    border-top: 0px;
}
th { 
  background: #33ccff;
  height: 40px; 
  color: black; 
  font-weight: bold;    
}
td, th { 
  padding: 8px; 
  text-align: left;
  border: 1px solid transparent; 
}
.iconhead { text-align: center; } 
.rowdata
{
    box-shadow: 1px 2px 6px 0px grey;
    border-radius: 4px;
    padding: 10px;
    margin-bottom: 5px;
    height:  50px;
    background: linear-gradient(to right, #33ccff 0%, #ff99cc 100%);
}
    .rowdata a{
    text-decoration: none;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    color: darkblue;

}

.btn:hover { 
            color: red;
            transition: .4s;
}
 
.rowdata i{  display: flex; justify-content: center; }
/* 
Max width before this PARTICULAR table gets nasty
This query will take effect for any screen smaller than 760px
and also iPads specifically.
*/
@media 
only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1000px)  {

	/* Force table to not be like tables anymore */
    
.rowdata
{
    height: auto;    
}
	table, thead, tbody, th, td, tr { 
		display: block; 
	}
	
	/* Hide table headers (but not display: none;, for accessibility) */
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	
	tr {  border: 1px solid #ccc; border-top: none; 
}
	td {
		/* Behave  like a "row" */
		position: relative;
		padding-left: 50%;
        text-align: center;
	}
	
	td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%; 
        padding-right: 10px; 
		white-space: nowrap;
	}
	
	td:nth-of-type(1):before { content: "Title"; }
	td:nth-of-type(2):before { content: "Discription"; }
	td:nth-of-type(3):before { content: "Completed"; }
	td:nth-of-type(4):before { content: "Edit"; }
	td:nth-of-type(5):before { content: "Remove"; }
}
           </style>
{% endblock editing %}

{% block currentpage %}HOME
{% endblock currentpage %}

{% block body %}
<div class="add-schedule" >
<i ><a class="fa fa-paper-plane"href="create/"> <span style="font-family:'Bebas Neue', cursive;" > Add Schedule </span></a></i>
</div>
<div class="counts"><p>
    {% if count == 0 %}<p>Congo!! You do not have any incompleted Tasks</p> {% else %}<p>you have <span style="color: aqua; font-size: 30px;" > {{count}}</span> tasks Incompleted right now!</p> {% endif %}
</div> 
<div class="table">
<table style="font-family: 'Fira Sans Condensed', sans-serif; " >
    <thead>
    <tr>
        <th>Title</th>
        <th >Discription</th>
        <th class="iconhead" >Completed</th>
        <th class="iconhead" >Edit</th>
        <th class="iconhead">Remove</th>
    </tr>
</thead>
    <tr>
        {% for task in object_list %}
    <div >    
    <tr class="rowdata">
        <td><span class="description" >{{task.title}}</span></td>
        <td ><span class="description" > {{task.desc}} </span></td>
        {% if task.complete == True %}
        <td> <i class="fa fa-check-circle" style="color:blue"></td></i></p> 
        {% else %} <td><p><i class="fa fa-times-circle" style="color:red"></i></p> </td>
        {% endif %} 
        <td><a href="task-update/{{task.id}}"><i  class="btn fa fa-edit"></i></></a></td>
        <td><a href="task-delete/{{task.id}}"><i class="btn fa fa-trash"></i></a></td>
    </tr>
    </div>
    {% empty %}
    <h1>EMPTY NOW</h1>
    {%endfor%}
    </tr>

</table>
{% endblock body %}
</div>

mailproject/maillapp/templates/maillapp/taskdelete.html
{% extends 'maillapp/main.html' %}
{% block editing %}
<style>    
    .btn:hover {
        background: #ff99cc;
        transition: .3s;
    }
    .btn {
        padding: 10px 20px 10px 20px;
        cursor: pointer;
        color: black;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        border-radius: 5px;
        border: .1px solid grey;
        box-shadow: 1px 2px 4px grey;
        font-size: 15px;
        background: #33ccff;
        margin-top: 20px;
    }
    .completed{ font-family: 'Lobster', cursive; font-size: 20px;
    }
    .task { color: #33ccff; }    
    .attribute{ font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; margin-top: 20px;  }

</style>
{% endblock editing %}
{% block body %}

    {% if task.complete == False %}<p class='completed' >You did not complete this task! Sure delete it?</p>{% else %}<p class='completed' >No! Worries you have already completed this task</p> {% endif %}
    <form method="POST">
        {% csrf_token %}
        <p class="attribute" >Task: <span class="task" >{{task.title}}</span></p>
        <p class="attribute" >Description: <span class="task" >{{task.desc}}</span></p>
        <p class="attribute">Completed: <span class="task" >{{task.complete}}</span></p>
    
        <input class='btn' type="submit" value="Delete">
    </form>
{% endblock body %} 
{% block currentpage %}Delete{% endblock currentpage %}

mailproject/maillapp/templates/maillapp/taskdetail.html
{% extends 'maillapp/main.html' %}
{% block editing %}
<style>
.navbar
{
    padding: 0%;
    margin: 0%;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
</style>
{% endblock editing %}

mailproject/maillapp/templates/maillapp/taskform.html
{% extends 'maillapp/main.html' %}

{% block editing %}
<style>
    * {
        text-align: center;
    }

    .container form{
        margin-top: 20px;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
    #id_title {
        font-size: 15px;
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid #33ccff;
    }

    #id_title:hover,
    #id_desc:hover {
        border: 1px solid #ff99cc;
    }

    #id_desc {
        font-size: 15px;
        padding: 10px;
        border: 1px solid #33ccff;
        width: 80%;
    }
    #id_complete

    {
         
        margin-bottom: 20px;
}
    .heading {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: black;
        font-size: 25px;
    }

    .btn:hover {
        background: #ff99cc;
        transition: .3s;
    }

    .btn {
        padding: 10px 20px 10px 20px;
        cursor: pointer;
        color: black;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        border-radius: 5px;
        border: .1px solid grey;
        box-shadow: 1px 2px 4px grey;
        font-size: 15px;
        background: #33ccff
    }
    .container
    {
        text-align: center;
    }
</style>

{% endblock editing %}
{% block currentpage %}Create & Edit{% endblock currentpage %}
{% block body %}
<h1 class='heading'>Create Your schedule</h1>
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}} <br>
        <input class="btn" type="submit">
    </form>
</div>
{% endblock body %}